// AUTO-GENERATED by gen_component.js -- do not hand-edit.
// Typed icon registry for the Alyvon icon system (spec section 8).
//
// Source of truth for glyph shapes: components/icons/svg/*.svg (one SVG per
// icon, Lucide-only, 24px grid / 2px stroke / round caps & joins / no fills).
// This component renders the equivalent lucide-react glyphs (same package
// already pinned in package.json) through a single wrapper that enforces the
// same construction rules, so the site gets a typed, tree-shakeable API
// without a second build step to inline raw SVG files.
//
// Usage:
//   import { Icon } from "@/components/icons";
//   <Icon name="department-content" className="h-6 w-6 text-accent" />
//
// Rules encoded here (do not override per-call):
//   - stroke="currentColor" only -- never pass a hardcoded hex color.
//   - strokeWidth is fixed at 2 -- components/ui/icon-wrapper.tsx was migrated
//     to the same 2px stroke width (ratified icon-system spec, 2026-07-29), so
//     this is now the single stroke-width convention sitewide. See README.md.
//   - Do not scale past 32px (h-8 w-8) without redrawing at a larger optical
//     size -- this wrapper does not stop you, but the spec prohibits it.
"use client";

import * as React from "react";
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Bell,
  BookOpen,
  Bot,
  BotMessageSquare,
  BriefcaseBusiness,
  Building2,
  CalendarCheck,
  ChartColumn,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheckBig,
  CircleDollarSign,
  CircleHelp,
  CircleX,
  ClipboardCheck,
  Clock,
  Cloud,
  Code,
  Compass,
  ContactRound,
  Copy,
  Cpu,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  GitBranch,
  Globe,
  Handshake,
  Headphones,
  HeartHandshake,
  House,
  Image,
  ImagePlus,
  Info,
  Kanban,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Link2,
  List,
  LoaderCircle,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageSquare,
  Microscope,
  Minus,
  Network,
  Paintbrush,
  Palette,
  Pencil,
  PenTool,
  Phone,
  PhoneOutgoing,
  Plug,
  Plus,
  Puzzle,
  RefreshCw,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  SquareCheckBig,
  Star,
  Tag,
  Target,
  Trash2,
  TrendingUpDown,
  TriangleAlert,
  Upload,
  User,
  UserPlus,
  Users,
  UsersRound,
  Video,
  WandSparkles,
  Workflow,
  X,
  Zap,
} from "lucide-react";

export const ICON_REGISTRY = {
  "nav-board": LayoutGrid,
  "nav-workforce": Users,
  "nav-routines": Zap,
  "nav-library": BookOpen,
  "nav-approvals": ClipboardCheck,
  "nav-improvement-engine": RefreshCw,
  "nav-custom-agents": UserPlus,
  "nav-integrations": Plug,
  "nav-activity": Activity,
  "nav-settings": Settings,
  "nav-marketing-hub": LayoutDashboard,
  "nav-crm": ContactRound,
  "nav-automations": Workflow,
  "nav-ai-employee": Bot,
  "nav-custom-ai": WandSparkles,
  "nav-analytics": ChartColumn,
  "nav-pricing": Tag,
  "nav-security": ShieldCheck,
  "department-content": FileText,
  "department-research": Microscope,
  "department-brand": Palette,
  "department-sales-development": PhoneOutgoing,
  "department-marketing-operations": SlidersHorizontal,
  "department-strategy-leadership": Compass,
  "department-brand-content": Paintbrush,
  "department-marketing-sales": Megaphone,
  "department-customer-people": Handshake,
  "department-product-engineering": Cpu,
  // The 11 department icons below complete the confirmed canonical 16-department
  // list (canonical counts live in lib/site.ts WORKFORCE_STATS — do not hardcode a
  // specialist number in comments; it drifts). Combined
  // with the 5 confirmed/live-routed icons above (content, research, brand,
  // sales-development, marketing-operations), the registry now has one icon per
  // department. The 5 org-chart cluster icons above (brand-content, marketing-sales,
  // customer-people, product-engineering, strategy-leadership) are left in place
  // for backward compatibility but are not part of the 16-department count.
  "department-communications-pr": Megaphone,
  "department-creative": PenTool,
  "department-customer-success": HeartHandshake,
  "department-customer-support": Headphones,
  "department-engineering": Code,
  "department-executive-strategy": Compass,
  "department-finance-accounting": CircleDollarSign,
  "department-people-hr": UsersRound,
  "department-product-design": Layers,
  "department-revenue-operations": TrendingUpDown,
  "department-security-compliance": ShieldCheck,
  "check": Check,
  "check-circle": CircleCheckBig,
  "close": X,
  "close-circle": CircleX,
  "plus": Plus,
  "minus": Minus,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "external-link": ExternalLink,
  "download": Download,
  "upload": Upload,
  "copy": Copy,
  "trash": Trash2,
  "edit": Pencil,
  "filter": Filter,
  "search": Search,
  "clock": Clock,
  "calendar": CalendarCheck,
  "mail": Mail,
  "phone": Phone,
  "send": Send,
  "bell": Bell,
  "star": Star,
  "alert-triangle": TriangleAlert,
  "help-circle": CircleHelp,
  "info": Info,
  "eye": Eye,
  "eye-off": EyeOff,
  "lock": Lock,
  "globe": Globe,
  "link": Link2,
  "share": Share2,
  "home": House,
  "menu": Menu,
  "user": User,
  "users": UsersRound,
  "building": Building2,
  "credit-card": CreditCard,
  "database": Database,
  "server": Server,
  "cloud": Cloud,
  "image": Image,
  "image-plus": ImagePlus,
  "video": Video,
  "code": Code,
  "file": File,
  "list": List,
  "kanban": Kanban,
  "network": Network,
  "message": MessageSquare,
  "bot-message": BotMessageSquare,
  "chart-pie": ChartPie,
  "square-check": SquareCheckBig,
  "badge-check": BadgeCheck,
  "rocket": Rocket,
  "puzzle": Puzzle,
  "layers": Layers,
  "briefcase": BriefcaseBusiness,
  "dollar-sign": CircleDollarSign,
  "trending": TrendingUpDown,
  "target": Target,
  "git-branch": GitBranch,
  "map-pin": MapPin,
  "loader": LoaderCircle,
} as const;

export type IconName =
  | "alert-triangle"
  | "arrow-left"
  | "arrow-right"
  | "badge-check"
  | "bell"
  | "bot-message"
  | "briefcase"
  | "building"
  | "calendar"
  | "chart-pie"
  | "check"
  | "check-circle"
  | "chevron-down"
  | "chevron-left"
  | "chevron-right"
  | "clock"
  | "close"
  | "close-circle"
  | "cloud"
  | "code"
  | "copy"
  | "credit-card"
  | "database"
  | "department-brand"
  | "department-brand-content"
  | "department-communications-pr"
  | "department-content"
  | "department-creative"
  | "department-customer-people"
  | "department-customer-success"
  | "department-customer-support"
  | "department-engineering"
  | "department-executive-strategy"
  | "department-finance-accounting"
  | "department-marketing-operations"
  | "department-marketing-sales"
  | "department-people-hr"
  | "department-product-design"
  | "department-product-engineering"
  | "department-research"
  | "department-revenue-operations"
  | "department-sales-development"
  | "department-security-compliance"
  | "department-strategy-leadership"
  | "dollar-sign"
  | "download"
  | "edit"
  | "external-link"
  | "eye"
  | "eye-off"
  | "file"
  | "filter"
  | "git-branch"
  | "globe"
  | "help-circle"
  | "home"
  | "image"
  | "image-plus"
  | "info"
  | "kanban"
  | "layers"
  | "link"
  | "list"
  | "loader"
  | "lock"
  | "mail"
  | "map-pin"
  | "menu"
  | "message"
  | "minus"
  | "nav-activity"
  | "nav-ai-employee"
  | "nav-analytics"
  | "nav-approvals"
  | "nav-automations"
  | "nav-board"
  | "nav-crm"
  | "nav-custom-agents"
  | "nav-custom-ai"
  | "nav-improvement-engine"
  | "nav-integrations"
  | "nav-library"
  | "nav-marketing-hub"
  | "nav-pricing"
  | "nav-routines"
  | "nav-security"
  | "nav-settings"
  | "nav-workforce"
  | "network"
  | "phone"
  | "plus"
  | "puzzle"
  | "rocket"
  | "search"
  | "send"
  | "server"
  | "share"
  | "square-check"
  | "star"
  | "target"
  | "trash"
  | "trending"
  | "upload"
  | "user"
  | "users"
  | "video";

export interface IconProps extends Omit<React.SVGProps<SVGSVGElement>, "width" | "height" | "stroke" | "strokeWidth" | "fill"> {
  name: IconName;
}

/**
 * Icon -- the single typed entry point for the Alyvon icon system.
 * Always 24px grid / 2px stroke / round caps & joins / no fills / currentColor.
 */
export const Icon = React.forwardRef<SVGSVGElement, IconProps>(
  ({ name, className, ...props }, ref) => {
    const Glyph = ICON_REGISTRY[name];
    if (!Glyph) return null;
    return (
      <Glyph
        ref={ref}
        className={className}
        stroke="currentColor"
        strokeWidth={2}
        strokeLinecap="round"
        strokeLinejoin="round"
        fill="none"
        aria-hidden={props["aria-label"] ? undefined : true}
        {...props}
      />
    );
  }
);
Icon.displayName = "Icon";

export default Icon;
